# Apollo Config
dynamictp.apollo.namespace                      = application
dynamictp.config-file-type                      = properties

dynamictp.web.core-pool-size                    = 10
dynamictp.web.maximum-pool-size                 = 200
dynamictp.web.keep-alive-time                   = 60
dynamictp.web.notify.receives                   = xxx

dynamictp.notify-platforms.platform             = DING
dynamictp.notify-platforms.url                  = https://oapi.dingtalk.com/robot/send?access_token=xxx

dynamictp.executors[0].thread-pool-id           = dynamictp-producer
dynamictp.executors[0].core-pool-size           = 10
dynamictp.executors[0].maximum-pool-size        = 24
dynamictp.executors[0].keep-alive-time          = 19999
dynamictp.executors[0].work-queue               = ResizableCapacityLinkedBlockingQueue
dynamictp.executors[0].queue-capacity           = 10000
dynamictp.executors[0].rejected-handler         = CallerRunsPolicy
dynamictp.executors[0].allow-core-thread-time-out = false
dynamictp.executors[0].notify.receives          = xxx
dynamictp.executors[0].notify.interval          = 10
dynamictp.executors[0].alarm.enable             = true
dynamictp.executors[0].alarm.queue-threshold    = 80
dynamictp.executors[0].alarm.active-threshold   = 80

dynamictp.executors[1].thread-pool-id           = dynamictp-consumer
dynamictp.executors[1].core-pool-size           = 10
dynamictp.executors[1].maximum-pool-size        = 20
dynamictp.executors[1].keep-alive-time          = 9999
dynamictp.executors[1].work-queue               = LinkedBlockingQueue
dynamictp.executors[1].queue-capacity           = 1024
dynamictp.executors[1].rejected-handler         = AbortPolicy
dynamictp.executors[1].allow-core-thread-time-out = true
dynamictp.executors[1].notify.receives          = xxx
dynamictp.executors[1].notify.interval          = 10
dynamictp.executors[1].alarm.enable             = true
dynamictp.executors[1].alarm.queue-threshold    = 80
dynamictp.executors[1].alarm.active-threshold   = 80
